version: "3"
services:
  postgres_db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    networks: 
      - backend
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: example
  web:
    build: .
    links:
      - postgres_db
    ports:
      - 8000:8000
    networks: 
      - backend
    environment:
      POSTGRES_HOST: postgres_db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DATABASE: postgres

networks:
  backend: